# Generated by Django 5.1.6 on 2025-04-01 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_historial_pedido_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_pedido',
            name='estado_seguimiento',
            field=models.CharField(choices=[('IN REVIEW', 'IN REVIEW'), ('PENDING', 'PENDING'), ('CUT-OFF', 'CUT-OFF'), ('PACKAGING', 'PACKAGING'), ('CUT-OFF-PENDING', 'CUT-OFF-PENDING'), ('CUT-OFF-ACCEPTED', 'CUT-OFF-ACCEPTED'), ('PACKAGING-PENDING', 'PACKAGING-PENDING'), ('PACKAGING-ACCEPTED', 'PACKAGING-ACCEPTED'), ('SHIPPED', 'SHIPPED'), ('CANCELLED', 'CANCELLED')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historial_pedido',
            name='hora',
            field=models.TimeField(default=datetime.time(11, 25, 10, 883234)),
        ),
        migrations.AlterField(
            model_name='historial_stock',
            name='hora_historial_stock',
            field=models.TimeField(default=datetime.time(11, 25, 10, 869882)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('IN REVIEW', 'IN REVIEW'), ('PENDING', 'PENDING'), ('CUT-OFF', 'CUT-OFF'), ('PACKAGING', 'PACKAGING'), ('CUT-OFF-PENDING', 'CUT-OFF-PENDING'), ('CUT-OFF-ACCEPTED', 'CUT-OFF-ACCEPTED'), ('PACKAGING-PENDING', 'PACKAGING-PENDING'), ('PACKAGING-ACCEPTED', 'PACKAGING-ACCEPTED'), ('SHIPPED', 'SHIPPED'), ('CANCELLED', 'CANCELLED')], max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='hora_registro',
            field=models.TimeField(default=datetime.time(11, 25, 10, 881485)),
        ),
    ]
